baseURL = 'https://romejiang.top/'
languageCode = 'zh-cn'
title = "Rome Jiang's Blog"
theme = 'yinyang'
DefaultContentLanguage = "zh"

[author]
  
  link = "https://romejiang.top"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    tabWidth = 2
    codeFences = true
    guessSyntax = true
    

[params]
headTitle = "Rome Jiang's Blog"
mainSections = ["posts"]
twitterCards = true
postHeaderContent = ""
postFooterContent = "<br/><br/><p>Subscribe：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Romejiang's Blog</a></p>"

author.name = "romejiang"
author.email = "Romejiang@gmail.com"
homepage = "https://romejiang.top/"
extraCSSFiles = ["css/index.css","css/syntax.css"]

[[params.socials]]
name = "About Me"
link = "/about"
[[params.socials]]
name = "Tags"
link = "/categories/"
[[params.socials]]
name = "Github"
link = "https://github.com/romejiang"


[module]
[[module.mounts]]
    excludeFiles = [
      'Blockchain/*',
    ]
    source = 'blogs'
    target = 'content/posts'